apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: portfolio-backend:observability
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: mongo
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/portfoliodb
            - name: SPRING_DATASOURCE_USERNAME
              value: portfolio
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: mysql-password
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017/portfolio_audit
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: jwt-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: portfolio
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
