apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources.default | nindent 12 }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: mongo
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/portfoliodb
            - name: SPRING_DATASOURCE_USERNAME
              value: portfolio
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: mysql-password
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017/portfolio_audit
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: jwt-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
